name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@master
      with:
        name: bash-static
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
